import {
  Organization,
  EmployeeAttendance,
  EnrolledEmployee,
  ShiftEntry,
  PaymentInvoice,
  PlanConfig,
  KioskDevice,
  AuditLogEntry,
  SupportTicket,
} from '@/types';

export const INITIAL_PLANS: PlanConfig[] = [
  {
    tier: 'STARTER',
    name: 'Visagel Starter',
    pricePerMonth: 49,
    maxEmployees: 50,
    maxDevices: 2,
    cloudSync: true,
    dailyReports: true,
    prioritySupport: false,
    customFieldsAllowed: false,
  },
  {
    tier: 'GROWTH',
    name: 'Visagel Growth',
    pricePerMonth: 129,
    maxEmployees: 250,
    maxDevices: 6,
    cloudSync: true,
    dailyReports: true,
    prioritySupport: true,
    customFieldsAllowed: true,
  },
  {
    tier: 'ENTERPRISE',
    name: 'Visagel Enterprise',
    pricePerMonth: 299,
    maxEmployees: 1000,
    maxDevices: 25,
    cloudSync: true,
    dailyReports: true,
    prioritySupport: true,
    customFieldsAllowed: true,
  },
  {
    tier: 'UNLIMITED',
    name: 'Visagel Global Unlimited',
    pricePerMonth: 599,
    maxEmployees: 10000,
    maxDevices: 100,
    cloudSync: true,
    dailyReports: true,
    prioritySupport: true,
    customFieldsAllowed: true,
  },
];

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-1',
    orgId: 'ORG-BRAN-001',
    name: 'Branzept Technologies Pvt Ltd',
    slug: 'branzept',
    contactPerson: 'Kiran Kumar',
    contactEmail: 'admin@branzept.com',
    contactPhone: '+91 98765 43210',
    address: 'Tech Park, Sector 5, Bangalore, India',
    secretApiKey: 'vg_live_89fa21980cf28ba49208a9',
    clientAppLoginUrl: 'visagel://login?org=ORG-BRAN-001&key=vg_live_89fa21980cf28ba49208a9',
    webPortalUrl: 'https://app.visagel.ai/portal/ORG-BRAN-001',
    plan: 'UNLIMITED',
    paymentStatus: 'PAID',
    billingCycle: 'LIFETIME',
    planPrice: 0,
    subscriptionStartDate: '2026-01-01',
    subscriptionEndDate: '2099-12-31',
    lastPaymentDate: '2026-01-01',
    nextBillingDate: '-',
    deviceQuota: 25,
    activeDeviceCount: 4,
    employeeQuota: 1000,
    enrolledEmployeeCount: 142,
    status: 'ACTIVE',
    notes: 'Headquarters deployment with 4 entrance iPad terminals.',
    createdAt: '2026-01-01T10:00:00Z',
    databaseConfig: {
      isolationMode: 'ISOLATED_CLUSTER',
      databaseName: 'visagel_tenant_branzept',
      clusterEndpoint: 'dedicated-node-branzept.visagel.internal:27017',
      collectionPrefix: 'punches',
      vectorIndexName: 'idx_vector_face_embeddings',
      backupS3Bucket: 's3://visagel-enterprise-isolated/ORG-BRAN-001',
      maxPoolSize: 200,
      sslEnabled: true,
      status: 'CONNECTED',
      lastPingLatencyMs: 2,
      totalStorageBytes: 1975684000,
    },
    apiKeys: [
      {
        id: 'key-bran-01',
        name: 'Main Gate Kiosk Biometric Stream Key',
        keyPrefix: 'vg_live_89fa21980cf2...',
        fullKeySecret: 'vg_live_89fa21980cf28ba49208a9',
        scope: 'KIOSK_STREAM',
        rateLimitPerMin: 1200,
        status: 'ACTIVE',
        createdAt: '2026-01-01T10:00:00Z',
        lastUsedAt: 'Just now',
        totalCalls24h: 3420,
      },
      {
        id: 'key-bran-02',
        name: 'Internal HR ERP Auto-Sync Webhook',
        keyPrefix: 'vg_live_99ca34812be0...',
        fullKeySecret: 'vg_live_99ca34812be09812401f11',
        scope: 'READ_WRITE',
        rateLimitPerMin: 600,
        status: 'ACTIVE',
        createdAt: '2026-02-15T09:12:00Z',
        lastUsedAt: '12 mins ago',
        totalCalls24h: 890,
      },
    ],
    customEndpoints: [
      { id: 'ep-1', route: '/api/v2/punch/verify-face', method: 'POST', rateLimit: 1200, isEnabled: true, avgLatencyMs: 18, successRate: '99.98%' },
      { id: 'ep-2', route: '/api/v2/roster/sync-employees', method: 'POST', rateLimit: 300, isEnabled: true, avgLatencyMs: 34, successRate: '100%' },
      { id: 'ep-3', route: '/api/v2/kiosks/heartbeat', method: 'POST', rateLimit: 600, isEnabled: true, avgLatencyMs: 4, successRate: '100%' },
      { id: 'ep-4', route: '/api/v2/reports/daily-csv-export', method: 'GET', rateLimit: 60, isEnabled: true, avgLatencyMs: 45, successRate: '99.90%' },
    ],
    admins: [
      {
        id: 'adm-101',
        name: 'Kiran Kumar',
        loginId: 'admin',
        password: 'adminPassword123',
        role: 'SUPER_ADMIN',
        email: 'admin@branzept.com',
        phone: '+91 98765 43210',
        isActive: true,
        createdAt: '2026-01-01T10:00:00Z',
        lastLoginAt: '2026-08-24T06:30:00Z',
      },
      {
        id: 'adm-102',
        name: 'Sarah Connor',
        loginId: 'hr_sarah',
        password: 'sarahSecure2026',
        role: 'HR_MANAGER',
        email: 'sarah.hr@branzept.com',
        phone: '+91 98765 43211',
        isActive: true,
        createdAt: '2026-02-15T09:12:00Z',
        lastLoginAt: '2026-08-23T16:45:00Z',
      },
    ],
  },
  {
    id: 'org-2',
    orgId: 'ORG-NEXUS-042',
    name: 'Nexus Finance',
    slug: 'nexus-finance',
    contactPerson: 'David Chen',
    contactEmail: 'dchen@nexusfintech.io',
    contactPhone: '+1 (415) 890-3412',
    address: 'Market St, San Francisco, CA, USA',
    secretApiKey: 'vg_live_bc12984fe76a100234190c',
    clientAppLoginUrl: 'visagel://login?org=ORG-NEXUS-042&key=vg_live_bc12984fe76a100234190c',
    webPortalUrl: 'https://app.visagel.ai/portal/ORG-NEXUS-042',
    plan: 'GROWTH',
    paymentStatus: 'PAID',
    billingCycle: 'MONTHLY',
    planPrice: 129,
    subscriptionStartDate: '2026-05-10',
    subscriptionEndDate: '2026-09-10',
    lastPaymentDate: '2026-08-10',
    nextBillingDate: '2026-09-10',
    deviceQuota: 6,
    activeDeviceCount: 2,
    employeeQuota: 250,
    enrolledEmployeeCount: 88,
    status: 'ACTIVE',
    notes: 'Two branch offices in SF & Austin.',
    createdAt: '2026-05-10T11:00:00Z',
    admins: [
      {
        id: 'adm-201',
        name: 'David Chen',
        loginId: 'nexus_master',
        password: 'NexusAdminSecure!',
        role: 'SUPER_ADMIN',
        email: 'dchen@nexusfintech.io',
        phone: '+1 415 890 3412',
        isActive: true,
        createdAt: '2026-05-10T11:00:00Z',
        lastLoginAt: '2026-08-24T02:15:00Z',
      },
    ],
  },
  {
    id: 'org-3',
    orgId: 'ORG-APEX-890',
    name: 'Apex Logistics & Warehouse',
    slug: 'apex-logistics',
    contactPerson: 'Rajesh Verma',
    contactEmail: 'ops@apexlogistics.in',
    contactPhone: '+91 99887 76655',
    address: 'Industrial Area Phase 2, Mumbai, India',
    secretApiKey: 'vg_live_77190caef45990234198cc',
    clientAppLoginUrl: 'visagel://login?org=ORG-APEX-890&key=vg_live_77190caef45990234198cc',
    webPortalUrl: 'https://app.visagel.ai/portal/ORG-APEX-890',
    plan: 'GROWTH',
    paymentStatus: 'OVERDUE',
    billingCycle: 'MONTHLY',
    planPrice: 129,
    subscriptionStartDate: '2026-04-01',
    subscriptionEndDate: '2026-08-15',
    lastPaymentDate: '2026-07-15',
    nextBillingDate: '2026-08-15',
    deviceQuota: 6,
    activeDeviceCount: 3,
    employeeQuota: 250,
    enrolledEmployeeCount: 160,
    status: 'SUSPENDED',
    notes: 'Payment reminder sent on Aug 18th.',
    createdAt: '2026-04-01T08:30:00Z',
    admins: [
      {
        id: 'adm-301',
        name: 'Rajesh Verma',
        loginId: 'apex_admin',
        password: 'ApexLogistics99',
        role: 'SUPER_ADMIN',
        email: 'ops@apexlogistics.in',
        isActive: true,
        createdAt: '2026-04-01T08:30:00Z',
      },
    ],
  },
  {
    id: 'org-4',
    orgId: 'ORG-AURA-112',
    name: 'Aura Studios',
    slug: 'aura-studios',
    contactPerson: 'Elena Rostova',
    contactEmail: 'elena@auradesign.co',
    contactPhone: '+44 20 7946 0912',
    address: 'Soho Square, London, UK',
    secretApiKey: 'vg_live_3309aef882109cd987110e',
    clientAppLoginUrl: 'visagel://login?org=ORG-AURA-112&key=vg_live_3309aef882109cd987110e',
    webPortalUrl: 'https://app.visagel.ai/portal/ORG-AURA-112',
    plan: 'STARTER',
    paymentStatus: 'PENDING',
    billingCycle: 'MONTHLY',
    planPrice: 49,
    subscriptionStartDate: '2026-08-18',
    subscriptionEndDate: '2026-09-18',
    lastPaymentDate: '2026-08-18',
    nextBillingDate: '2026-09-18',
    deviceQuota: 2,
    activeDeviceCount: 1,
    employeeQuota: 50,
    enrolledEmployeeCount: 22,
    status: 'TRIAL',
    notes: 'Currently on 14-day Pro Trial evaluation.',
    createdAt: '2026-08-18T14:20:00Z',
    admins: [
      {
        id: 'adm-401',
        name: 'Elena Rostova',
        loginId: 'aura_elena',
        password: 'ElenaDesign2026',
        role: 'SUPER_ADMIN',
        email: 'elena@auradesign.co',
        isActive: true,
        createdAt: '2026-08-18T14:20:00Z',
      },
    ],
  },
];

export const INITIAL_ATTENDANCE: EmployeeAttendance[] = [
  {
    id: 'att-1',
    orgId: 'ORG-BRAN-001',
    orgName: 'Branzept Technologies Pvt Ltd',
    employeeId: 'BR-001',
    name: 'Ravi Kiran',
    department: 'Engineering',
    date: '2026-08-24',
    punches: [
      { id: 'p-1', type: 'IN', time: '08:42:09 am', timestamp: 1787541129000 },
      { id: 'p-2', type: 'OUT', time: '01:15:30 pm', timestamp: 1787557530000 },
      { id: 'p-3', type: 'IN', time: '02:00:15 pm', timestamp: 1787560215000 },
    ],
    totalWorkingHours: '5 hrs 45 mins',
    status: 'PRESENT',
  },
  {
    id: 'att-2',
    orgId: 'ORG-BRAN-001',
    orgName: 'Branzept Technologies Pvt Ltd',
    employeeId: 'BR-026',
    name: 'John Doe',
    department: 'Engineering',
    date: '2026-08-24',
    punches: [
      { id: 'p-4', type: 'IN', time: '09:05:10 am', timestamp: 1787542510000 },
    ],
    status: 'PRESENT',
  },
  {
    id: 'att-3',
    orgId: 'ORG-BRAN-001',
    orgName: 'Branzept Technologies Pvt Ltd',
    employeeId: 'BR-027',
    name: 'Sarah Connor',
    department: 'Design',
    date: '2026-08-24',
    punches: [
      { id: 'p-5', type: 'IN', time: '09:48:22 am', timestamp: 1787545102000 },
    ],
    status: 'LATE',
  },
  {
    id: 'att-4',
    orgId: 'ORG-NEXUS-042',
    orgName: 'Nexus Finance',
    employeeId: 'NX-104',
    name: 'Alexander Pierce',
    department: 'Security',
    date: '2026-08-24',
    punches: [
      { id: 'p-6', type: 'IN', time: '08:55:00 am', timestamp: 1787541900000 },
      { id: 'p-7', type: 'OUT', time: '05:30:20 pm', timestamp: 1787572820000 },
    ],
    totalWorkingHours: '8 hrs 35 mins',
    status: 'PRESENT',
  },
  {
    id: 'att-5',
    orgId: 'ORG-NEXUS-042',
    orgName: 'Nexus Finance',
    employeeId: 'NX-209',
    name: 'Maya Lin',
    department: 'Product',
    date: '2026-08-24',
    punches: [
      { id: 'p-8', type: 'IN', time: '09:12:40 am', timestamp: 1787542960000 },
    ],
    status: 'PRESENT',
  },
];

export const INITIAL_EMPLOYEES: EnrolledEmployee[] = [
  {
    id: 'emp-1',
    orgId: 'ORG-BRAN-001',
    orgName: 'Branzept Technologies Pvt Ltd',
    employeeId: 'BR-001',
    name: 'Ravi Kiran',
    department: 'Engineering',
    phone: '+91 98765 43200',
    joiningDate: '2026-07-15',
    photoUri: null,
    status: 'ACTIVE',
    customData: { BloodGroup: 'O+', EmergencyContact: '+91 98765 00000' },
  },
  {
    id: 'emp-2',
    orgId: 'ORG-BRAN-001',
    orgName: 'Branzept Technologies Pvt Ltd',
    employeeId: 'BR-026',
    name: 'John Doe',
    department: 'Engineering',
    phone: '+91 98765 43210',
    joiningDate: '2026-08-01',
    photoUri: null,
    status: 'ACTIVE',
    customData: { BloodGroup: 'A+', EmergencyContact: '+91 98765 11111' },
  },
  {
    id: 'emp-3',
    orgId: 'ORG-BRAN-001',
    orgName: 'Branzept Technologies Pvt Ltd',
    employeeId: 'BR-027',
    name: 'Sarah Connor',
    department: 'Design',
    phone: '+91 98765 43211',
    joiningDate: '2026-08-10',
    photoUri: null,
    status: 'ACTIVE',
  },
  {
    id: 'emp-4',
    orgId: 'ORG-BRAN-001',
    orgName: 'Branzept Technologies Pvt Ltd',
    employeeId: 'BR-028',
    name: 'Michael Scott',
    department: 'HR & Admin',
    phone: '+91 98765 43212',
    joiningDate: '2026-08-12',
    photoUri: null,
    status: 'ACTIVE',
  },
  {
    id: 'emp-5',
    orgId: 'ORG-NEXUS-042',
    orgName: 'Nexus Finance',
    employeeId: 'NX-104',
    name: 'Alexander Pierce',
    department: 'Security',
    phone: '+1 415 890 1122',
    joiningDate: '2026-03-01',
    photoUri: null,
    status: 'ACTIVE',
  },
  {
    id: 'emp-6',
    orgId: 'ORG-NEXUS-042',
    orgName: 'Nexus Finance',
    employeeId: 'NX-209',
    name: 'Maya Lin',
    department: 'Product',
    phone: '+1 415 890 3344',
    joiningDate: '2026-04-15',
    photoUri: null,
    status: 'ACTIVE',
  },
];

export const INITIAL_SHIFTS: ShiftEntry[] = [
  {
    id: 'sh-1',
    orgId: 'ORG-BRAN-001',
    name: 'General Day Shift',
    startHour: 9,
    startMin: 0,
    endHour: 18,
    endMin: 0,
    lateCutoffHour: 9,
    lateCutoffMin: 30,
    isActive: true,
  },
  {
    id: 'sh-2',
    orgId: 'ORG-BRAN-001',
    name: 'Night Production Shift',
    startHour: 21,
    startMin: 0,
    endHour: 6,
    endMin: 0,
    lateCutoffHour: 21,
    lateCutoffMin: 30,
    isActive: false,
  },
  {
    id: 'sh-3',
    orgId: 'ORG-NEXUS-042',
    name: 'Standard US Core',
    startHour: 8,
    startMin: 30,
    endHour: 17,
    endMin: 30,
    lateCutoffHour: 9,
    lateCutoffMin: 0,
    isActive: true,
  },
];

export const INITIAL_INVOICES: PaymentInvoice[] = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2026-001',
    orgId: 'ORG-BRAN-001',
    orgName: 'Branzept Technologies Pvt Ltd',
    amount: 3588,
    currency: 'USD',
    paymentDate: '2026-01-01',
    dueDate: '2026-01-01',
    status: 'PAID',
    billingCycle: 'ANNUAL',
    planTier: 'ENTERPRISE',
    paymentMethod: 'Wire Transfer',
    transactionRef: 'WT-89410-BRAN',
  },
  {
    id: 'inv-102',
    invoiceNumber: 'INV-2026-088',
    orgId: 'ORG-NEXUS-042',
    orgName: 'Nexus Finance',
    amount: 129,
    currency: 'USD',
    paymentDate: '2026-08-10',
    dueDate: '2026-08-10',
    status: 'PAID',
    billingCycle: 'MONTHLY',
    planTier: 'GROWTH',
    paymentMethod: 'Credit Card',
    transactionRef: 'CC-90123-NEXUS',
  },
  {
    id: 'inv-103',
    invoiceNumber: 'INV-2026-092',
    orgId: 'ORG-APEX-890',
    orgName: 'Apex Logistics & Warehouse',
    amount: 129,
    currency: 'USD',
    paymentDate: '',
    dueDate: '2026-08-15',
    status: 'OVERDUE',
    billingCycle: 'MONTHLY',
    planTier: 'GROWTH',
    paymentMethod: 'Invoice',
  },
  {
    id: 'inv-104',
    invoiceNumber: 'INV-2026-099',
    orgId: 'ORG-AURA-112',
    orgName: 'Aura Design Studios',
    amount: 49,
    currency: 'USD',
    paymentDate: '',
    dueDate: '2026-09-01',
    status: 'PENDING',
    billingCycle: 'MONTHLY',
    planTier: 'STARTER',
    paymentMethod: 'Credit Card',
  },
];

export const INITIAL_KIOSKS: KioskDevice[] = [
  {
    id: 'ksk-1',
    deviceId: 'KSK-BRAN-01',
    name: 'HQ Main Entrance iPad Air',
    orgId: 'ORG-BRAN-001',
    orgName: 'Branzept Technologies Pvt Ltd',
    location: 'Main Reception Turnstile 1',
    deviceType: 'iPad',
    ipAddress: '192.168.1.104',
    status: 'ONLINE',
    lastHeartbeat: 'Just now',
    faceEngineVersion: 'v2.4.8 (CoreML Accelerated)',
    activeFaceModelCount: 142,
  },
  {
    id: 'ksk-2',
    deviceId: 'KSK-BRAN-02',
    name: 'HQ R&D Wing Kiosk',
    orgId: 'ORG-BRAN-001',
    orgName: 'Branzept Technologies Pvt Ltd',
    location: 'Floor 3 Server Room Access',
    deviceType: 'Dedicated Terminal',
    ipAddress: '192.168.1.108',
    status: 'ONLINE',
    lastHeartbeat: '1 min ago',
    faceEngineVersion: 'v2.4.8 (CoreML Accelerated)',
    activeFaceModelCount: 65,
  },
  {
    id: 'ksk-3',
    deviceId: 'KSK-NEXUS-01',
    name: 'SF Branch Lobby Terminal',
    orgId: 'ORG-NEXUS-042',
    orgName: 'Nexus Finance',
    location: 'Tower A 12th Floor Lobby',
    deviceType: 'iPad',
    ipAddress: '10.0.4.15',
    status: 'ONLINE',
    lastHeartbeat: 'Just now',
    faceEngineVersion: 'v2.4.8',
    activeFaceModelCount: 88,
  },
  {
    id: 'ksk-4',
    deviceId: 'KSK-APEX-01',
    name: 'Mumbai Warehouse Gate A',
    orgId: 'ORG-APEX-890',
    orgName: 'Apex Logistics & Warehouse',
    location: 'Loading Dock Entry 1',
    deviceType: 'Android Tablet',
    ipAddress: '172.16.0.42',
    status: 'OFFLINE',
    lastHeartbeat: '2 hours ago (Network issue)',
    faceEngineVersion: 'v2.3.2',
    activeFaceModelCount: 160,
  },
  {
    id: 'ksk-5',
    deviceId: 'KSK-AURA-01',
    name: 'Soho Studio Front Door',
    orgId: 'ORG-AURA-112',
    orgName: 'Aura Studios',
    location: 'Main Reception Desk',
    deviceType: 'iPad',
    ipAddress: '192.168.0.88',
    status: 'SYNCING',
    lastHeartbeat: '5 mins ago',
    faceEngineVersion: 'v2.4.8',
    activeFaceModelCount: 22,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-101',
    timestamp: '2026-08-24 16:45:10',
    actor: 'Super Admin (super@visagel.ai)',
    actorRole: 'SUPER_ADMIN',
    action: 'Backend Health Check',
    details: 'All microservices operational: MongoDB 2ms latency, Node REST healthy, 10 Kiosks connected.',
    severity: 'INFO',
  },
  {
    id: 'log-102',
    timestamp: '2026-08-24 14:12:00',
    actor: 'Kiran Kumar',
    actorRole: 'SUPER_ADMIN',
    action: 'Kiosk Terminal Registered',
    details: 'Provisioned KSK-AURA-01 for Aura Studios with direct app login link.',
    targetOrgId: 'ORG-AURA-112',
    severity: 'INFO',
  },
  {
    id: 'log-103',
    timestamp: '2026-08-24 10:30:22',
    actor: 'System Automated Engine',
    actorRole: 'SYSTEM',
    action: 'Payment Overdue Alert',
    details: 'Apex Logistics & Warehouse (ORG-APEX-890) subscription invoice INV-2026-092 passed due date.',
    targetOrgId: 'ORG-APEX-890',
    severity: 'WARNING',
  },
  {
    id: 'log-104',
    timestamp: '2026-08-23 18:00:00',
    actor: 'David Chen',
    actorRole: 'SUPER_ADMIN',
    action: 'Admin Password Reset',
    details: 'Updated security credentials for nexus_master admin user.',
    targetOrgId: 'ORG-NEXUS-042',
    severity: 'INFO',
  },
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'tck-101',
    ticketNumber: 'TCK-BRAN-2401',
    orgId: 'ORG-BRAN-001',
    orgName: 'Branzept Technologies Pvt Ltd',
    title: 'Entrance iPad Kiosk 2 Offline Heartbeat Alert',
    description: 'The iPad Air terminal situated at Floor 3 Server Room has not dispatched a heartbeat socket ping in 25 minutes. Local buffer mode enabled.',
    category: 'Hardware Kiosk & Terminal',
    priority: 'CRITICAL_URGENT',
    status: 'IN_PROGRESS',
    slaHours: 1,
    slaStatus: 'WITHIN_SLA',
    createdBy: 'Automated Telemetry Bot',
    createdByRole: 'SYSTEM_BOT',
    assignedTo: 'Vikram Mehta (Visagel L2 Support)',
    relatedDeviceId: 'KSK-BRAN-02',
    isAutoFlagged: true,
    createdAt: '2026-08-24T14:30:00Z',
    updatedAt: '2026-08-24T14:45:00Z',
    messages: [
      {
        id: 'msg-1',
        senderName: 'Visagel Telemetry Watchdog',
        senderRole: 'SYSTEM_BOT',
        senderOrgName: 'Visagel Core Engine',
        message: 'CRITICAL: KSK-BRAN-02 failed 3 consecutive WebSocket health checks at 14:30:00. Offline punch fallback engaged.',
        timestamp: '2026-08-24T14:30:00Z',
        isInternalNote: false,
      },
      {
        id: 'msg-2',
        senderName: 'Vikram Mehta',
        senderRole: 'VISAGEL_ADMIN',
        senderOrgName: 'Visagel Support Desk',
        message: 'Internal Note: Checked AWS Node-1 socket logs. The terminal IP 192.168.1.108 shows local Wi-Fi packet drop. Pinging Branzept network admin.',
        timestamp: '2026-08-24T14:35:00Z',
        isInternalNote: true,
      },
      {
        id: 'msg-3',
        senderName: 'Vikram Mehta',
        senderRole: 'VISAGEL_ADMIN',
        senderOrgName: 'Visagel Support Desk',
        message: 'Hello Branzept Team, we detected a Wi-Fi disconnect on your Floor 3 kiosk. All biometric punches are safely saved locally on the device and will sync automatically once network resumes.',
        timestamp: '2026-08-24T14:40:00Z',
        isInternalNote: false,
      },
    ],
  },
  {
    id: 'tck-102',
    ticketNumber: 'TCK-BRAN-2402',
    orgId: 'ORG-BRAN-001',
    orgName: 'Branzept Technologies Pvt Ltd',
    title: 'Request for New R&D Staff Biometric Vector Batch Sync',
    description: 'We have onboarded 15 new engineers in the AI division. Need confirmation that their face models are distributed across both active kiosks.',
    category: 'Biometrics & AI Vector Sync',
    priority: 'HIGH',
    status: 'OPEN',
    slaHours: 4,
    slaStatus: 'WITHIN_SLA',
    createdBy: 'Sarah Connor (HR Manager)',
    createdByRole: 'CLIENT_ADMIN',
    assignedTo: 'Ananya Sharma (Visagel Support)',
    relatedDeviceId: 'KSK-BRAN-01',
    isAutoFlagged: false,
    createdAt: '2026-08-24T11:15:00Z',
    updatedAt: '2026-08-24T11:15:00Z',
    messages: [
      {
        id: 'msg-201',
        senderName: 'Sarah Connor',
        senderRole: 'CLIENT_ADMIN',
        senderOrgName: 'Branzept Technologies Pvt Ltd',
        message: 'Hello Visagel Support, 15 new employee profiles have been registered in the dashboard. Can you confirm the vector weights are broadcast to Main Gate iPad Air 5?',
        timestamp: '2026-08-24T11:15:00Z',
        isInternalNote: false,
      },
    ],
  },
  {
    id: 'tck-103',
    ticketNumber: 'TCK-NEXUS-2399',
    orgId: 'ORG-NEXUS-042',
    orgName: 'Nexus Finance',
    title: 'Shift Overtime Calculation Discrepancy on Night Roster',
    description: 'The late-night shift closing at 02:00 AM did not automatically mark overtime hours for 3 finance analysts.',
    category: 'Employee Roster & Shifts',
    priority: 'MEDIUM',
    status: 'AWAITING_CLIENT_RESPONSE',
    slaHours: 8,
    slaStatus: 'WITHIN_SLA',
    createdBy: 'David Chen',
    createdByRole: 'CLIENT_ADMIN',
    assignedTo: 'Vikram Mehta (Visagel L2 Support)',
    isAutoFlagged: false,
    createdAt: '2026-08-23T16:00:00Z',
    updatedAt: '2026-08-24T09:30:00Z',
    messages: [
      {
        id: 'msg-301',
        senderName: 'David Chen',
        senderRole: 'CLIENT_ADMIN',
        senderOrgName: 'Nexus Finance',
        message: 'Night shift punches for analysts on Aug 22nd showed standard 8 hours instead of 10.5 hours with OT.',
        timestamp: '2026-08-23T16:00:00Z',
        isInternalNote: false,
      },
      {
        id: 'msg-302',
        senderName: 'Vikram Mehta',
        senderRole: 'VISAGEL_ADMIN',
        senderOrgName: 'Visagel Support Desk',
        message: 'Hi David, we inspected your shift configuration. The Night Roster had the cutoff set to 23:59. We updated the overnight boundary logic. Could you please review and confirm?',
        timestamp: '2026-08-24T09:30:00Z',
        isInternalNote: false,
      },
    ],
  },
  {
    id: 'tck-104',
    ticketNumber: 'TCK-APEX-2388',
    orgId: 'ORG-APEX-890',
    orgName: 'Apex Logistics & Warehouse',
    title: 'Loading Dock Android Tablet Camera Alignment Check',
    description: 'Employees reporting 2-3 second delay in low-light conditions at Warehouse Gate A entrance terminal.',
    category: 'Hardware Kiosk & Terminal',
    priority: 'HIGH',
    status: 'RESOLVED',
    slaHours: 4,
    slaStatus: 'WITHIN_SLA',
    createdBy: 'Rajesh Verma',
    createdByRole: 'CLIENT_ADMIN',
    assignedTo: 'Ananya Sharma (Visagel Support)',
    relatedDeviceId: 'KSK-APEX-01',
    isAutoFlagged: false,
    createdAt: '2026-08-22T08:00:00Z',
    updatedAt: '2026-08-23T12:00:00Z',
    resolvedAt: '2026-08-23T12:00:00Z',
    messages: [
      {
        id: 'msg-401',
        senderName: 'Rajesh Verma',
        senderRole: 'CLIENT_ADMIN',
        senderOrgName: 'Apex Logistics & Warehouse',
        message: 'Face scans taking too long at 6 AM during dark shift changes.',
        timestamp: '2026-08-22T08:00:00Z',
        isInternalNote: false,
      },
      {
        id: 'msg-402',
        senderName: 'Ananya Sharma',
        senderRole: 'VISAGEL_ADMIN',
        senderOrgName: 'Visagel Support Desk',
        message: 'Remotely enabled Screen Flash Fill-Light mode on KSK-APEX-01 firmware config. Low light confidence increased from 82% to 99.4%. Marking resolved.',
        timestamp: '2026-08-23T12:00:00Z',
        isInternalNote: false,
      },
    ],
  },
];


